# Generated by Django 4.2.11 on 2024-03-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='Altura',
            new_name='pAltura',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='CPF',
            new_name='pCPF',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Data_Nasc',
            new_name='pData',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Nome',
            new_name='pNome',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Peso',
            new_name='pPeso',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Sexo',
            new_name='pSexo',
        ),
    ]
