# Generated by Django 4.2.11 on 2024-03-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_rename_altura_pessoa_paltura_rename_cpf_pessoa_pcpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pAltura',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pPeso',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
