# Generated by Django 4.2.11 on 2024-03-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_alter_pessoa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
